---
- hosts: "{{ server | default('production') }}"
  vars_files:
    - ../../group_vars/production/zeppelin
  tasks:
    - name: stop zeppelin server
      shell:
        cmd: "{{zeppelin_home_dir}}/bin/zeppelin-daemon.sh stop"

# vim: et sw=2 ts=2:
