---
# tasks file for roles/zeppelin

- block:

  - name: mkdir zeppelin
    file:
      path: /opt/zeppelin
      state: directory


  - name: downlaod zeppelin
    get_url:
      url: http://ftp.jaist.ac.jp/pub/apache/zeppelin/zeppelin-0.8.2/zeppelin-{{zeppelin_version}}-bin-netinst.tgz
      dest: /opt/zeppelin/
      force: no

  - name: unarchive zeppelin package
    unarchive:
      src: /opt/zeppelin/zeppelin-{{zeppelin_version}}-bin-netinst.tgz
      dest: /opt/zeppelin
      creates: /opt/zeppelin/zeppelin-{{zeppelin_version}}-bin-netinst/README.md

  - name: configure alternatives
    alternatives:
      name: zeppelin
      link: /opt/zeppelin/default
      path: /opt/zeppelin/zeppelin-{{zeppelin_version}}-bin-netinst

  tags:
    - zeppelin